### ISSUE TITLE
os missmatch bug trigger but this package

### ISSUE THREAD

**Issue by ilovejs** [client9/shlib#18]
`curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin vX.Y.Z
`

# yield

`golangci/golangci-lint crit uname_os_check 'MINGW64_NT-10.0' got converted to 'mingw64_nt-10.0' which is not a GOOS value. Please file bug at https://github.com/client9/shlib`

**Comment by syntaqx** [comment]
🤔 Freaking MinGW man.. seems like we're never going to get ahead of it. Do you have any particular thoughts on a solution? It's currently working for me as I haven't upgraded and now I'm semi not excited to...

**Comment by vonas** [comment]
```
$  curl https://raw.githubusercontent.com/nektos/act/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9641  100  9641    0     0  28779      0 --:--:-- --:--:-- --:--:-- 28865
nektos/act crit uname_os_check 'MINGW64_NT-6.1-7601' got converted to 'mingw64_n
t-6.1-7601' which is not a GOOS value. Please file bug at https://github.com/cli
ent9/shlib
```
see: **https://github.com/nektos/act#installation**
