### ISSUE TITLE
uname_os_check: internal error

### ISSUE THREAD

**Issue by lawdaywa** [client9/shlib#3]
I am having an issue with installing a project using this set of scripts and the error message says to file a bug here.
I am atempting to use [goreleaser](https://github.com/goreleaser/goreleaser) to install [apex/up](https://github.com/apex/up) on windows 10 Home version: 1703 build: 15063.540
I haven't yet tried to replicate this issue on another windows machine as I am limited at the moment.
I did not have this issue on a virtual machine running ubuntu. 
The error I am receiving is: 
```
/usr/bin/sh: uname_os_check: internal error 'MSYS_NT-10.0' got converted to 'msys_nt-10.0' which is not a GOOS value. Please file bug
at https://github.com/client9/shlib
```
and the script I am attempting to use to install  [apex/up](https://github.com/apex/up) is this\:
```
curl -sfL "https://raw.githubusercontent.com/apex/up/master/install.sh" | sh
```
I have noticed that on my machine, **uname** returns\:
```
C:\>uname
MSYS_NT-10.0
```
Whereas on an ubuntu virtual machine I happened to have running, **uname** returns\:
```
vagrant@homestead:~$ uname
Linux
```
The **uname_os_check** script appears to be looking for the value "windows" on windows machines but it receives "MSYS_NT-10.0" instead, I am not sure if this is the desired behavior. 
The administrator of [apex/up](https://github.com/apex/up) believed that it might be a  [goreleaser](https://github.com/goreleaser/goreleaser) issue but I am coming here first. 
P.S. I'm not sure if it is good etiquette to put a thank you at the bottom of a new issue but ill put it anyways,
Thank you for your time.

**Comment by client9** [comment]
hmm just saw this.

**Comment by AlekSi** [comment]
@client9 Are you sure that commit fixes this issue? I'm seeing this error while installing golangci-lint on Windows on Travis CI:
```
golangci/golangci-lint crit uname_os_check 'MSYS_NT-10.0' got converted to 'msys_nt-10.0' which is not a GOOS value. Please file bug at https://github.com/client9/shlib
```

* https://travis-ci.org/AlekSi/gosh/jobs/450423969
* https://github.com/golangci/golangci-lint/blob/master/install.sh

**Comment by XVilka** [comment]
Still met this issue while installing Antibody: https://getantibody.github.io/install/
```
└> > curl -sfL git.io/antibody | sh -s - -b /usr/bin
getantibody/antibody crit uname_os_check 'MSYS_NT-10.0-16299' got converted to 'msys_nt-10.0-16299' which is not a GOOS value. Please file bug at https://github.com/client9/shlib
```
