### ISSUE TITLE
shellcheck   travis-ci vs. docker vs. downloader installs

### ISSUE THREAD

**Issue by client9** [client9/shlib#9]
* travis-ci installs an (old) version of shell check
* GitHub has binary releases
* there is an official docker image too

Need to figure out which to so local dev and travis do the same thing

**Comment by client9** [comment]
travis-ci uses 0.46, current is 0.47 from https://github.com/koalaman/shellcheck/releases

```
$ shellcheck -V
ShellCheck - shell script analysis tool
version: 0.4.6
license: GNU General Public License, version 3
website: http://www.shellcheck.net
```

**Comment by syntaqx** [comment]
Looks like the current release is 0.6.0 and the released `apt-get install` is the same, closing.
